os: linux
language: bash
services:
  - docker

stages: 
  - hello
  - restful
  - restful-32

jobs:
  include:
    - stage: hello
      name: "Hello World"
      script: 
        - docker build -t hello hello/
        - docker run hello
        - docker images
  
    - stage: restful
      name: "Harbour RESTful"
      script: 
        - docker build -t restful restful/
        - docker run -d --rm -p 8002:8002 restful
        - docker ps
        - curl http://localhost:8002/v1/statusType -v
        - docker images
        
    - stage: restful-32
      name: "RESTful on Harbour 3.2"
      allow_failures: 
        script:
          - docker build -t restful restful/
          - docker run -d --rm -p 8002:8002 restful
          - docker ps
          - curl http://localhost:8002/v1/statusType -v
          - docker images